### ISSUE TITLE
Swift with -O and map method magic

### ISSUE THREAD

**Issue by Igor-Palaguta** [ReactiveCocoa/ReactiveCocoa#1632]
In one swift file I have

```
let enabledBlock = RACSignal.combineLatest([oneSignal, anotherSignal]).map {
//some code
}

 self.verifyButton.rac_command = RACCommand(enabled: enabledBlock, signalBlock: verifySignalBlock)
```

and in another swift file I have also signal with map like:

```
signal.map {
            (next: AnyObject!) -> AnyObject! in
            return "\(next)"
}
```

Everything work fine in debug. But in Release with -O in first file instead of passed map block called block from second file. If I comment code from second file, I still have this problem, map block from third file is called in first file. I think it relates to swift, not to reactive cocoa. I am fixing this by replacing blocks with functions like:

```
signal.map(numberToString)
```

Has anybody else this issue too?

**Comment by mac-cain13** [comment]
Is there already someone who can confirm whether this issue still occurs with Swift 1.2 / XCode 6.3?

**Comment by Igor-Palaguta** [comment]
Just checked one of cases. It was fixed in XCode 6.3

**Comment by calebd** [comment]
Just got bit by this. Yuck.

**Comment by robertjpayne** [comment]
I just got hit by this too – still broken for Xcode 6.2, massive weirdness all around with ReactiveCocoa and -Ofast

**Comment by Igor-Palaguta** [comment]
Can't replicate it anymore on Xcode 6.3

**Comment by carl1990** [comment]
I have same pronlem

this is my code:

RACSignal.combineLatest([phoneNumEdit.rac_textSignal(), passportEdit.rac_textSignal()]).map {
            let tuple = $0 as! RACTuple
            let account = tuple.first as! String
            if account.isEmpty {
                self.phoneNum.text = ""
            } else {
                self.phoneNum.text = "手机号"
            }
            let password = tuple.second as! String
            if password.isEmpty {
                self.password.text = ""
            } else {
                self.password.text = "密码"
            }
            if (account.isValidMobileNumber()) && (password.isValidPassword()) {
                self.loginBtn.enabled = true
                self.loginBtn.backgroundColor = UIColor.whiteColor()
            } else {
                self.loginBtn.enabled = false
                self.loginBtn.backgroundColor = UIColor.grayColor()
            }
        }

but `map` block is not invoked,how can I resolve this problem

**Comment by ikesyo** [comment]
@carl1990 It seems that you are not subscribing to the resulting signal of `map`, which returns a new signal.

**Comment by carl1990** [comment]
and use `and()`method and also not work, so How can I capture this signal

**Comment by ikesyo** [comment]
Could you please see the documentaions:

- https://github.com/ReactiveCocoa/ReactiveCocoa/blob/v2.5/Documentation/BasicOperators.md
- https://github.com/ReactiveCocoa/ReactiveCocoa/blob/v2.5/Documentation/FrameworkOverview.md

You need `subscribeNext`.
