### ISSUE TITLE
[Question] RAC 3 How do I take the result of an inner signal? 

### ISSUE THREAD

**Issue by LightD** [ReactiveCocoa/ReactiveCocoa#1993]
Here's my situation:
I need request a token from the server on the first request from my app, so I want to happen automatically and then it continues the other request.. here's my attempt (won't compile, I'm just trying):
``` swift
private func RPCRequest(method: URLRequestConvertible) -> Signal<JSONRPCResponse, NSError> {
        if !MyLocalAuthenticator.IsAuthenticated() {
            
            let authSignal = Alamofire.Manager.sharedInstance.reactiveRequest(Router.Authenticate)
            
            
            let mappedSignal = authSignal |> map { data -> Bool in
                
                MyLocalAuthenticator.DidAuthenticateWithToken(data.result as! String)
                
                // now this should execute the "else" statement.. the actual request that we need
                self.RPCRequest(method)
                return true
            }
            
            
            // how do I return the result of the inner signal here? or like return the inner signal?
           return theInnerRecursiveReuqestOrSmthn
        }
        else {
            return Alamofire.Manager.sharedInstance.reactiveRequest(method)
        }
}
```

In the above example, `mappedSignal` is `Signal<Bool, NSError>`.. if I replace the `-> Bool` with `-> Signal<JSONRPCResponse, NSError>` in the map function then the `mappedSignal` will be of type `Signal<Signal<JSONRPCResponse,NSError>, NSError>`.. 

Of course, needless to say, `reactiveRequest` is a small wrapper around Alamofire request that turns it into reactive request..

**Comment by larryonoff** [comment]
You need apply ```flatten(.Concat)``` to ```Signal<Signal<JSONRPCResponse,NSError>, NSError>``` or apply ```flatMap(.Concat) { ... }``` instead of ```map { ... }``` to ```authSignal```

**Comment by LightD** [comment]
Ok so `flatten(.Concat)` actually worked.. thank you so much :rocket: 
But how do I use flatMap? I couldn't use it, the compiler complains about
>/blablabla/NetworkEngine.swift:32:32: Binary operator '|>' cannot be applied to operands of type 'SignalProducer<JSONRPCResponse, NSError>' and 'SignalProducer<JSONRPCResponse, NSError>?'
I just changed `map { ... }` to `flatMap(FlattenStrategy.Concat) { ... }`, could you help? I didn't find examples of `flatMap` in the unit test coverage, as far as I remember...

**Comment by larryonoff** [comment]
The same construction didn't also work for me. I assume that compiler doesn't understand which of ```flatMap``` to use. So you should use full signature of the flatMap without any shortening. Try try specify type of data
```swift
let mappedSignal = authSignal |> flatMap(FlattenStrategy.Concat) { (data: NSData) -> SignalProducer<JSONRPCResponse, NSError> in

                MyLocalAuthenticator.DidAuthenticateWithToken(data.result as! String)

                return self.RPCRequest(method)
            }
```

**Comment by LightD** [comment]
that sounds nice, but whenever I try to use it the compiler mistakes it for the local swift implementation of `flatMap`.. I don't know why..

**Comment by NachoSoto** [comment]
That failure to infer the right method will probably be fixed by #1988.

**Comment by LightD** [comment]
Thank you @NachoSoto .. I will close this issue for now then.. I'll reopen it in case that doesn't resolve this :)
