### ISSUE TITLE
Skip repeats with dynamic property / optionals

### ISSUE THREAD

**Issue by ianbytchek** [ReactiveCocoa/ReactiveCocoa#3376]
I have a simple dynamic property with equitable value and want to use `skipRepeats()` on the property's signal without passing `==` or other comparison function. But it doesn't work because value is stored as optional and compiler doesn't pick it up. I tried extending the signal with the following, but then compiler says that `argument is passed to call that takes no arguments`:

```swift
extension Signal where Value: OptionalProtocol, Value.Wrapped: Equatable
{
    public func skipRepeats() -> ReactiveSwift.Signal<Value, Error> {
        return self.skipRepeats(==)
    }
}
```

I wouldn't call it a bug, it just seems that OptionalProtocol handling is not implemented? Is it possible to have it?

**Comment by andersio** [comment]
Yes, just that you can't use `==` directly since `OptionalProtocol where .Wrapped == Value` is statically not `Optional<Value>`. You need `{ $0.optional == $1.optional }`.

**Comment by ianbytchek** [comment]
@andersio this is awesome, thanks for the tip. Can we have this extension available as default?

**Comment by mdiep** [comment]
This should resolve itself in Swift 3.1, because `Optional` will become `Equatable` when `Value` is `Equatable`.

**Comment by andersio** [comment]
@mdiep Conditional conformance would probably land in Swift 4 though. In Swift 3.1 we can only drop `OptionalProtocol`. So perhaps we may still have an overload as an intermediate solution.

**Comment by mdiep** [comment]
Ah, okay. I still don't love adding an overload, but that starts to make more sense.
